// Generated by Wrangler on deployment
// This file is auto-generated, do not modify directly

interface Env {
  // D1 database binding
  DB: D1Database;
  
  // Add other bindings as needed
}

// Add any additional types or interfaces needed for your worker